name: Setup Repository Labels

on:
  workflow_call:

permissions:
  issues: write
  contents: read
jobs:
  setup-labels:
    runs-on: ubuntu-latest
    steps:
      - name: Check if labels already exist
        id: check-labels
        uses: actions/github-script@v7
        with:
          script: |
            try {
              const { data: labels } = await github.rest.issues.listLabelsForRepo({
                owner: context.repo.owner,
                repo: context.repo.repo
              });
              
              // 設定予定のラベルが既に存在するかチェック
              const targetLabels = ['deps', 'npm', 'security', 'major', 'ci'];
              const existingLabels = labels.map(label => label.name);
              const hasTargetLabels = targetLabels.some(label => existingLabels.includes(label));
              
              if (hasTargetLabels) {
                console.log('Target labels already exist. Skipping setup.');
                return 'skip';
              }
              
              return 'proceed';
            } catch (error) {
              console.error('Error checking labels:', error);
              return 'proceed';
            }

      - name: Setup Labels
        if: steps.check-labels.outputs.result == 'proceed'
        uses: actions/github-script@v7
        with:
          script: |
            const labels = [
              { name: 'deps', color: '0366d6', description: 'Pull requests that update a dependency file' },
              { name: 'npm', color: 'cb3837', description: 'Related to npm packages and Node.js dependencies' },
              { name: 'security', color: 'd73a4a', description: 'Security fixes and vulnerability patches' },
              { name: 'major', color: '6f42c1', description: 'Major-version dependency updates (breaking changes) to review carefully' },
              { name: 'ci', color: '0e8a16', description: 'CI / workflow related changes and maintenance' }
            ];

            for (const label of labels) {
              try {
                await github.rest.issues.createLabel({
                  owner: context.repo.owner,
                  repo: context.repo.repo,
                  name: label.name,
                  color: label.color,
                  description: label.description
                });
                console.log(`✅ Created label: ${label.name}`);
              } catch (error) {
                if (error.status === 422) {
                  console.log(`⚠️ Label already exists: ${label.name}`);
                } else {
                  console.error(`❌ Error creating label ${label.name}:`, error);
                }
              }
            }
